# User Settings
DEFAULT_USER=marco

# Behaviour
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2

# Theme
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(os_icon user dir)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vcs root_indicator time)
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MODE='awesome-patched'
POWERLEVEL9K_SHOW_CHANGESET=true

POWERLEVEL9K_OS_ICON_BACKGROUND="white"
POWERLEVEL9K_OS_ICON_FOREGROUND="black"

POWERLEVEL9K_USER_FOREGROUND="white"
POWERLEVEL9K_USER_BACKGROUND="cyan"

POWERLEVEL9K_DIR_HOME_FOREGROUND="white"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="white"
POWERLEVEL9K_DIR_ETC_FOREGROUND="white"
POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="white"

POWERLEVEL9K_DIR_HOME_BACKGROUND="233"
POWERLEVEL9K_DIR_HOME_SUBFOLDER_BACKGROUND="233"
POWERLEVEL9K_DIR_ETC_BACKGROUND="233"
POWERLEVEL9K_DIR_DEFAULT_BACKGROUND="233"

POWERLEVEL9K_HOME_ICON=''
POWERLEVEL9K_HOME_SUB_ICON=''
POWERLEVEL9K_FOLDER_ICON=''
POWERLEVEL9K_ETC_ICON=''

ZSH_THEME="powerlevel9k/powerlevel9k"

# Plugins
plugins=(
  git
  zsh-dircolors-solarized
  colored-man-pages
  zsh-syntax-highlighting
  zsh-autosuggestions
)

# Source
source $HOME/.aliases
source $ZSH/oh-my-zsh.sh
. $HOME/.zsh/plugins/bd/bd.zsh

